minecraft_version=1.21.1
loader_version=0.19.3
fabric_api_version=0.116.12+1.21.1
yarn_mappings=1.21.1+build.3
java_language_level=21
adapter_source_set=fabric1211
minecraft_dependency_range=~1.21.1
fabric_api_dependency_range=>=0.116.12
